### PR TITLE
Only update state index on register agent

### LINKED ISSUE #195: [BUG] Status changed to PROVISIONING when failed
### What is the bug?
```
[2023-11-24T03:01:22,448][ERROR][o.o.f.t.ProvisionWorkflowTransportAction] [ip-172-31-56-214] Provisioning failed for workflow IKRG_4sB9nj1vxRLOlJI : org.opensearch.flowframework.exception.FlowFrameworkException: java.lang.ClassCastException: class java.util.HashMap cannot be cast to class org.opensearch.ml.common.agent.LLMSpec (java.util.HashMap is in module java.base of loader 'bootstrap'; org.opensearch.ml.common.agent.LLMSpec is in unnamed module of loader java.net.FactoryURLClassLoader @2ba5aa7a)
[2023-11-24T03:01:22,470][INFO ][o.o.f.t.ProvisionWorkflowTransportAction] [ip-172-31-56-214] updated workflow IKRG_4sB9nj1vxRLOlJI state to PROVISIONING
```

### How can one reproduce the bug?
1. Try to create a case where the provisioning fails
2. Status changes to `PROVISIONING`

### What is the expected behavior?
Status should be changed to `FAILED`.

### What is your host/environment?
Ubuntu

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

### PR DESCRIPTION
**Pull request by amitgalitz**
### Description
Doesn't update state index if we are deploying a model, only on the register step
fixes logs regarding a failed provisioning
```
Provisioning failed for workflow: vst5N4wBXkf_uA_9Zltj
java.util.concurrent.CompletionException: java.util.concurrent.ExecutionException: org.opensearch.flowframework.exception.FlowFrameworkException: Can't find class for type https
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413) ~[?:?]
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at org.opensearch.flowframework.transport.ProvisionWorkflowTransportAction.executeWorkflow(ProvisionWorkflowTransportAction.java:205) [opensearch-flow-framework-2.11.0.0-SNAPSHOT.jar:2.11.0.0-SNAPSHOT]
	at org.opensearch.flowframework.transport.ProvisionWorkflowTransportAction.lambda$executeWorkflowAsync$4(ProvisionWorkflowTransportAction.java:171) [opensearch-flow-framework-2.11.0.0-SNAPSHOT.jar:2.11.0.0-SNAPSHOT]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:849) [opensearch-2.11.0.jar:2.11.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.util.concurrent.ExecutionException: org.opensearch.flowframework.exception.FlowFrameworkException: Can't find class for type https
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at org.opensearch.flowframework.workflow.ProcessNode.lambda$execute$2(ProcessNode.java:177) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	... 4 more
Caused by: org.opensearch.flowframework.exception.FlowFrameworkException: Can't find class for type https
	at org.opensearch.flowframework.workflow.CreateConnectorStep$1.onFailure(CreateConnectorStep.java:120) ~[?:?]
	at org.opensearch.ml.client.MachineLearningNodeClient.lambda$wrapActionListener$22(MachineLearningNodeClient.java:393) ~[?:?]
	at org.opensearch.core.action.ActionListener$1.onFailure(ActionListener.java:90) ~[opensearch-core-2.11.0.jar:2.11.0]
	at org.opensearch.action.support.TransportAction$1.onFailure(TransportAction.java:122) ~[opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.ml.action.connector.TransportCreateConnectorAction.doExecute(TransportCreateConnectorAction.java:118) ~[?:?]
	at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:218) ~[opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.indexmanagement.rollup.actionfilter.FieldCapsFilter.apply(FieldCapsFilter.kt:118) ~[?:?]
	at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:216) ~[opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.indexmanagement.controlcenter.notification.filter.IndexOperationActionFilter.apply(IndexOperationActionFilter.kt:39) ~[?:?]
	at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:216) ~[opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.performanceanalyzer.action.PerformanceAnalyzerActionFilter.apply(PerformanceAnalyzerActionFilter.java:78) ~[?:?]
	at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:216) ~[opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.action.support.TransportAction.execute(TransportAction.java:188) ~[opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.action.support.TransportAction.execute(TransportAction.java:107) ~[opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.client.node.NodeClient.executeLocally(NodeClient.java:110) ~[opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.client.node.NodeClient.doExecute(NodeClient.java:97) ~[opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:476) ~[opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.ml.client.MachineLearningNodeClient.createConnector(MachineLearningNodeClient.java:254) ~[?:?]
	at org.opensearch.flowframework.workflow.CreateConnectorStep.execute(CreateConnectorStep.java:172) ~[?:?]
	at org.opensearch.flowframework.workflow.ProcessNode.lambda$execute$2(ProcessNode.java:170) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	... 4 more
[2023-12-05T00:55:57,324][INFO ][o.o.f.t.ProvisionWorkflowTransportAction] [dev-dsk-amgalitz-2a-7bcc8589.us-west-2.amazon.com] updated workflow vst5N4wBXkf_uA_9Zltj state to FAILED
[2023-12-05T00:55:59,729][INFO ][o.o.m.c.MLSyncUpCron     ] [dev-dsk-amgalitz-2a-7bcc8589.us-west-2.amazon.com] ML configuration already initialized, no action needed
```

```
{
    "workflow_id": "-bOJN4wBXUgiQ-ZyDYZf",
    "state": "COMPLETED",
    "provisioning_progress": "DONE",
    "provision_start_time": 1701738784231,
    "provision_end_time": 1701738790096,
    "resources_created": [
        {
            "workflow_step_name": "register_agent",
            "workflow_step_id": "workflow_step_6",
            "agent_id": "-rOJN4wBXUgiQ-ZyJoYb"
        },
        {
            "workflow_step_name": "create_connector",
            "workflow_step_id": "workflow_step_1",
            "connector_id": "-7OJN4wBXUgiQ-ZyJ4bX"
        },
        {
            "workflow_step_name": "register_remote_model",
            "workflow_step_id": "workflow_step_2",
            "model_id": "_bOJN4wBXUgiQ-ZyKIa3"
        },
        {
            "workflow_step_name": "register_agent",
            "workflow_step_id": "workflow_step_8",
            "agent_id": "_7OJN4wBXUgiQ-ZyPIaq"
        }
    ]
}
```
### Issues Resolved

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by joshpalis — APPROVED** [review]

**Review by owaiskazi19 — APPROVED** [review]

File: src/main/java/org/opensearch/flowframework/workflow/AbstractRetryableWorkflowStep.java [hunk 1]
```diff
@@ -58,6 +59,24 @@ public AbstractRetryableWorkflowStep(
...
+     * @param resourceName resource name for the given step
+     * @param nodeId node ID of the given step
+     * @param workflowId workflow ID of the given workflow
+     * @param response Response from ml commons get Task API
+     * @param future CompletableFuture of the given step
+     */
+    public void completeFuture(String resourceName, String nodeId, String workflowId, MLTask response, CompletableFuture future) {
+        future.complete(
+            new WorkflowData(
+                Map.ofEntries(Map.entry(resourceName, response.getModelId()), Map.entry(REGISTER_MODEL_STATUS, response.getState().name())),
```
Comment (owaiskazi19) [inline src/main/java/org/opensearch/flowframework/workflow/AbstractRetryableWorkflowStep.java:73]: Need to add model_id too
