### PR TITLE
Fixed Template Update Location and Improved Logger Statements in ReprovisionWorkflowTransportAction

### LINKED ISSUE #870: [BUG] Reprovision Workflow IT is flaky
### What is the bug?

`FlowFrameworkRestApiIT.testReprovisionWorkflow()` is flaky.  During 2.17.0 release it required multiple retries to pass on Windows x86.  There are occasional GitHub CI failures on other platforms, see https://github.com/opensearch-project/flow-framework/actions/runs/10777769278/job/29887668921#step:4:59 (Ubuntu) and https://github.com/opensearch-project/flow-framework/actions/runs/10777865339/job/29888745661#step:4:49 (macOS)

```
FlowFrameworkRestApiIT > testReprovisionWorkflow FAILED
    org.junit.ComparisonFailure: expected:<[COMPLET]ED> but was:<[FAIL]ED>
        at __randomizedtesting.SeedInfo.seed([4D7D6[49](https://github.com/opensearch-project/flow-framework/actions/runs/10777865339/job/29888745661#step:4:50)945752BD3:196DC17D8E477B7D]:0)
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at org.opensearch.flowframework.FlowFrameworkRestTestCase.getAndAssertWorkflowStatus(FlowFrameworkRestTestCase.java:7[53](https://github.com/opensearch-project/flow-framework/actions/runs/10777865339/job/29888745661#step:4:54))
        at org.opensearch.flowframework.FlowFrameworkRestTestCase.lambda$getResourcesCreated$7(FlowFrameworkRestTestCase.java:805)
        at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1136)
        at org.opensearch.flowframework.FlowFrameworkRestTestCase.getResourcesCreated(FlowFrameworkRestTestCase.java:804)
        at org.opensearch.flowframework.rest.FlowFrameworkRestApiIT.testReprovisionWorkflow(FlowFrameworkRestApiIT.java:471)
```

### How can one reproduce the bug?

Run our CI repeatedly.  It fails reasonably often.

### What is the expected behavior?

Tests consistently pass.

### What is your host/environment?

Reproducible on Windows, Linux, macOS as shown above

### Do you have any additional context?

The failure is occurring consistently on the attempt to reprovision to remove default ingest pipeline (setting it to `_none`, which is the `SearchPipelineService.NOOP_PIPELINE_ID`).

The change in default pipeline name is the only difference in the two templates.

### PR DESCRIPTION
**Pull request by saimedhi**
### Description
This PR fixes the template update location in ReprovisionWorkflowTransportAction.java and enhances logger statements for better clarity and debugging.

### Related Issues
closes #870 

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/flow-framework/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java [hunk 1]
```diff
@@ -270,27 +270,45 @@ private void executeWorkflowAsync(
...
 
     /**
-     * Executes the given workflow sequence
+     * Replace template document
      * @param template The template to store after reprovisioning completes successfully
+     * @param workflowId The workflowId associated with the workflow that is executing
+     */
+    private void updateTemplate(Template template, String workflowId) {
+        flowFrameworkIndicesHandler.updateTemplateInGlobalContext(workflowId, template, ActionListener.wrap(templateResponse -> {
+            logger.info("Updated template for {}", workflowId, State.COMPLETED);
```
Comment (dbwiddis) [inline src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java:289]: The `State.COMPLETED` here is ignored as there's only one `{}` parameter. Which is a good thing because I thought it was out of place anyway, and should just be deleted.

File: src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java [hunk 2]
```diff
@@ -270,27 +270,45 @@ private void executeWorkflowAsync(
...
+        }, exception -> {
+            String errorMessage = "Failed to update use case template for " + workflowId;
+            logger.error(errorMessage, exception);
```
Comment (dbwiddis) [inline src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java:292]: Just put the message inline in the `logger.error()` with the substitution parameters.  (Yes I know you just refactored what was already there but we can improve it!)

File: src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java [hunk 3]
```diff
@@ -270,27 +270,45 @@ private void executeWorkflowAsync(
...
+    private void executeWorkflow(List<ProcessNode> workflowSequence, String workflowId) {
         String currentStepId = "";
         try {
             Map<String, PlainActionFuture<?>> workflowFutureMap = new LinkedHashMap<>();
             for (ProcessNode processNode : workflowSequence) {
                 List<ProcessNode> predecessors = processNode.predecessors();
                 logger.info(
                     "Queueing process [{}].{}",
-                    processNode.id(),
+                    processNode.id() + processNode.workflowStep().getName(),
```
Comment (dbwiddis) [inline src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java:311]: Have some sort of delimiter here, otherwise these two strings will run together.  As written assuming we're using the semantic search template, this will appear as `Queueing process [create_ingest_pipelineupdate_ingest_pipeline].`.  

Not sure the best way to do this but perhaps `[create_ingest_pipeline (update_ingest_pipeline)]`?  Open to other ideas.

**Review by dbwiddis — COMMENTED** [review]
I see it's in draft, offering an initial review.

File: src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java [hunk 4]
```diff
@@ -290,7 +306,7 @@ private void executeWorkflow(Template template, List<ProcessNode> workflowSequen
                 List<ProcessNode> predecessors = processNode.predecessors();
                 logger.info(
                     "Queueing process [{}].{}",
-                    processNode.id(),
+                    String.format("%s (type: %s)", processNode.id(), processNode.workflowStep().getName()),
```
Comment (dbwiddis) [inline src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java:309]: You shouldn't need to use `String.format()` with logger substitutions.  This should be achievable with something like `"Queueing Process [{} (type: {})].()"`

**Review by dbwiddis — COMMENTED** [review]
LGTM so far!

**Comment by amitgalitz** [comment]
Overall LGTM, just a quick question, in the case the reprovisioning itself fails, will have an issue that the template is updated and we need to roll that back?

**Review by amitgalitz — APPROVED** [review]

File: src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java [hunk 5]
```diff
@@ -270,12 +270,28 @@ private void executeWorkflowAsync(
         ActionListener<WorkflowResponse> listener
     ) {
         try {
-            threadPool.executor(PROVISION_WORKFLOW_THREAD_POOL).execute(() -> { executeWorkflow(template, workflowSequence, workflowId); });
+            threadPool.executor(PROVISION_WORKFLOW_THREAD_POOL).execute(() -> {
+                updateTemplate(template, workflowId);
```
Comment (joshpalis) [inline src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java:274]: One major concern I have here is error handling during subsequent executions. 

Reprovisioning depends on comparing the old template stored in the index with the new template configuration provided in the request body. We compare each node and identify which steps have been modified, creating a new workflow to either create new or update existing resources. 

Let's say we attempt to reprovision a workflow and it executes the first few steps and this fails at the end due to some transitive error. Since we've already indexed the updated template, we would be comparing the new template with itself. We will need to handle this case more gracefully and perhaps consider rolling back the attempted modification if a failure occurs, essentially returning the cluster to its state prior to the reprovision command. This is a similar approach that CloudFormation templates currently take.

Comment (dbwiddis) [reply src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java:274]: >  We will need to handle this case more gracefully and perhaps consider rolling back the attempted modification if a failure occurs, 

This is "fine grained deprovisioning" and the current code is not set up to support that.  To get to this level of granularity we're going to need to really figure out versioning (See #526).

For now let's focus on what the correct action is to take on this PR.

Currently when we provision, we save the template (in the desired to-be state) and then attempt to provision it.  If it's successful we know the template/state match.  If it fails, we don't know the state.  We may have partially deployed resources.  At this point, the only correct action is to deprovision (which ignores the template, and just gets rid of resources).

So, now consider reprovisioning.  Current state is to keep the old template there, and only update it after provisioning completes.  (But we currently set the workflow state to complete prior to updating the template which leads to a possible race condition (see the linked bug) where we can quickly reprovision again but not have the current template to compare to.   We absolutely must update the template before setting state to completed.

But why not update it earlier to match the behavior of provisioning?  Attempt to do so, if it fails, the only thing we can do is deprovision.

Here's a concrete example.
1. Provision a template with Step A and Step B.   
2. On success, state index has Resources A and B.
3. Now reprovision with a template with Step A, Step X, Step B, Step Y.
4. Step X completes successfully, state index has Resources A, B, and X.
5. Step Y fails for some reason.  

IF we haven't updated the template it has the old "A, B" steps and looking at the state you may wonder where X comes from or what additional steps are missing.  Worse, if you attempt to reprovision from here, you may get a conflict trying to add X again.  The only thing we can do is deprovision and start again from scratch, but we didn't save the "updated" template so we still need to save that template and provision with it.

If we have updated the template it has A, X, B, Y, and we can see "oh, we can manually add Y" if we're doing it interactively.  Or, we can just give up on it, deprovision completely, and provision completely... in which case the correct 4-step template is already there.  

In either failure case, we have to deprovision to recover automaticaly.   "Reprovisioning" is just a short cut to the deprovisoin/provision sequence in the happy case.  

Once you have a failure, you can't/shouldn't even try to reprovision because no matter what, the state index is out of sync.  In this case, I think having the latest "desired" template lets you do the full deprovision + provision existing template steps to get back in sync.

File: CHANGELOG.md [hunk 6]
```diff
@@ -25,6 +25,7 @@ Inspired from [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)
 - Incrementally remove resources from workflow state during deprovisioning ([#898](https://github.com/opensearch-project/flow-framework/pull/898))
 
 ### Bug Fixes
+- Fixed Template Update Location and Improved Logger Statements in ReprovisionWorkflowTransportAction ([#918](https://github.com/opensearch-project/flow-framework/pull/918))
 ### Infrastructure
```
Comment (dbwiddis) [inline CHANGELOG.md:29]: Nit: Needs a line of whitespace before the markdown header.
```suggestion
- Fixed Template Update Location and Improved Logger Statements in ReprovisionWorkflowTransportAction ([#918](https://github.com/opensearch-project/flow-framework/pull/918))

### Infrastructure
```

File: CHANGELOG.md [hunk 7]
```diff
@@ -7,10 +7,10 @@ Inspired from [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)
 ### Features
 ### Enhancements
 ### Bug Fixes
+- Fixed Template Update Location and Improved Logger Statements in ReprovisionWorkflowTransportAction ([#918](https://github.com/opensearch-project/flow-framework/pull/918))
```
Comment (dbwiddis) [inline CHANGELOG.md:10]: We are backporting this so it shouldn't go into 3.x section.

**Review by dbwiddis — APPROVED** [review]
Approved pending changelog fix and resolving @joshpalis comment.

File: src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java (hunk 5 above)
Comment (joshpalis) [reply src/main/java/org/opensearch/flowframework/transport/ReprovisionWorkflowTransportAction.java:274]: Thanks for the input Dan. These changes look good to me then until we can implement fine-grained deprovisioning. In this case, we can rely on documentation to indicate to the user to deprovision if reprovision failed.

**Review by joshpalis — APPROVED** [review]

File: CHANGELOG.md [hunk 8]
```diff
@@ -7,10 +7,10 @@ Inspired from [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)
...
 ### Infrastructure
 - Set Java target compatibility to JDK 21 ([#730](https://github.com/opensearch-project/flow-framework/pull/730))
 - Add knowledge base alert agent into sample templates ([#874](https://github.com/opensearch-project/flow-framework/pull/874))
-
```
Comment (dbwiddis) [inline CHANGELOG.md:13]: Don't remove this linebreak
