### PR TITLE
Remove useCase and defaultParams field in WorkflowRequest

### LINKED ISSUE #758: [BUG] WorkflowRequest doesn't serialize the use case and default parameters over transport
### What is the bug?

The `WorkflowRequest` class doesn't serialize the use case and default parameters over transport.

The `writeTo()` only writes the provision parameter and params map:
https://github.com/opensearch-project/flow-framework/blob/cf1016fd72e0f9196db498cbb52f4a57bafadade/src/main/java/org/opensearch/flowframework/transport/WorkflowRequest.java#L197-L206

Similarly, the constructor using `StreamInput` doesn't read them
https://github.com/opensearch-project/flow-framework/blob/cf1016fd72e0f9196db498cbb52f4a57bafadade/src/main/java/org/opensearch/flowframework/transport/WorkflowRequest.java#L128-L136

This was missed in unit testing because the tests incorrectly checked the original `workflowRequest` and not the `streamInputRequest` after passing through transport. (Note the last 4 lines.)
https://github.com/opensearch-project/flow-framework/blob/cf1016fd72e0f9196db498cbb52f4a57bafadade/src/test/java/org/opensearch/flowframework/transport/WorkflowRequestResponseTests.java#L155-L166

### How can one reproduce the bug?

Fix the unit test to properly test the workflow created from transport. Change lines 163-166 above to:
```java
        assertNull(streamInputRequest.validate());
        assertFalse(streamInputRequest.isProvision());
        // FAILS, `getDefaultParams()` is null
        assertTrue(streamInputRequest.getDefaultParams().isEmpty()); 
        // FAILS, `getUseCase()` is null
        assertEquals(streamInputRequest.getUseCase(), "cohere-embedding_model_deploy");
```

### What is the expected behavior?

If these fields are required to be part of the `WorkflowRequest` they should be properly serialized.  Note that adding these fields would break compatibility across versions and would require version-checking for the additional fields.

However, these fields are never accessed in the code, other than in the (failing) tests.  If they are not needed, they should be removed.

### Do you have any additional context?

The fields were added in #583.

The tests have been fixed in #757, with the failing tests commented out until this issue is resolved.

### PR DESCRIPTION
**Pull request by junweid62**
### Description
- Removed `useCase` And `defaultParams` since the WorkflowRequest class doesn't serialize the use case and default parameters over transport. 

- Also removed the constructor that has never been used in our code base

### Related Issues
Resolves #758 

### Check List
- [x] New functionality includes testing.
- ~[ ] New functionality has been documented.~
- ~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~
- [x] Commits are signed per the DCO using `--signoff`.
- ~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/flow-framework/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by joshpalis — APPROVED** [review]

File: src/test/java/org/opensearch/flowframework/transport/WorkflowRequestResponseTests.java [hunk 1]
```diff
@@ -153,69 +153,10 @@ public void testWorkflowRequestWithParams() throws IOException {
         assertEquals("bar", streamInputRequest.getParams().get("foo"));
     }
 
-    public void testWorkflowRequestWithUseCase() throws IOException {
```
Comment (dbwiddis) [inline src/test/java/org/opensearch/flowframework/transport/WorkflowRequestResponseTests.java:156]: Should these tests be fully removed, or just remove the parts related to the use case and params?  

Since that particular method of provisioning produces a different code path, it's useful to make sure the existing params match the expected

**Review by dbwiddis — COMMENTED** [review]
LGTM, but not sure if the removed tests are completely duplicated somewhere else or provide at least one interesting change worth testing (even if not the new params)

**Review by dbwiddis — APPROVED** [review]
> Also removed the constructor that has never been used in our code base

Although this comment seems to be the "new thing" that was tested so probably good to remove.
