### PR TITLE
Reset workflow state to initial state after successful deprovision

### LINKED ISSUE #578: [BUG] Deprovision doesn't remove the error field if it exists
### What is the bug?
If provisioning has a failure on one of the steps we write to the error field in the state index. However when we deprovision that same workflow we don't remove the error message from the document in the workflow state index.
### How can one reproduce the bug?
1. Provision with an expected failure (easy way is to provision a pipeline with a processor that isn't in your cluster)
2.Deprovision the same workflow:

resulting state index:

```
            {
                "_index": ".plugins-flow-framework-state",
                "_id": "QljrPY4BJDcxHyOJPUNd",
                "_score": 1.0,
                "_source": {
                    "workflow_id": "QljrPY4BJDcxHyOJPUNd",
                    "state": "NOT_STARTED",
                    "provisioning_progress": "NOT_STARTED",
                    "provision_start_time": 1710435961112,
                    "resources_created": [],
                    "provision_end_time": 1710435828966,
                    "error": "org.opensearch.flowframework.exception.WorkflowStepException during step create_ingest_pipeline, restStatus: BAD_REQUEST"
                }
            }
            
```
### What is the expected behavior?

error field shouldn't be there anymore
### Potential solution

Some potential solution
1. We can either simply place the error field as an empty string, however this isn't prefered because if the error field wasn't there to begin with now we have the field with just `"error": ""`. 
2. You can't directly remove the field through update, this has to be done through a script as far as I know. You also can't provide both a contentMap(doc) and a script in the same update request. This means we either have to just update the logic here https://github.com/opensearch-project/flow-framework/blob/main/src/main/java/org/opensearch/flowframework/transport/DeprovisionWorkflowTransportAction.java#L230 to update with a script that removes the error field if it exists (e.g `"if (ctx._source.contains(error)) { ctx._source.remove('error)}"`) and updates the other fields accordingly or we have to make two update operations, one with the current way we do it with a new doc and another with the painless script

### PR DESCRIPTION
**Pull request by dbwiddis**
### Description

On successful deprovision, resets the workflow state to its initial state, rather than simply updating the fields.

### Issues Resolved

Fixes #578 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by joshpalis — APPROVED** [review]

**Review by ohltyler — APPROVED** [review]

File: src/main/java/org/opensearch/flowframework/transport/DeprovisionWorkflowTransportAction.java [hunk 1]
```diff
@@ -246,7 +242,7 @@ private void updateWorkflowState(
                 Map.ofEntries(
                     Map.entry(STATE_FIELD, State.COMPLETED),
                     Map.entry(PROVISIONING_PROGRESS_FIELD, ProvisioningProgress.DONE),
-                    Map.entry(PROVISION_START_TIME_FIELD, Instant.now().toEpochMilli()),
+                    Map.entry(PROVISION_END_TIME_FIELD, Instant.now().toEpochMilli()),
```
Comment (amitgalitz) [inline src/main/java/org/opensearch/flowframework/transport/DeprovisionWorkflowTransportAction.java:245]: is there a new provision end time when we fail deprovisioning? Is the end time here not when the provisioning itself ends (last step is executed), unrelated to deprovisioning?
