### PR TITLE
Fix and Refactor Test with Builder Pattern for Issue #2825

### LINKED ISSUE #858: [BUG] Compile failure with new MLTask Constructor
### What is the bug?

https://github.com/opensearch-project/ml-commons/pull/2825 added a new parameter to the constructor.  We use that in a test:
> src/test/java/org/opensearch/flowframework/workflow/RegisterLocalPretrainedModelStepTests.java:140: error: no suitable constructor found for MLTask(String,String,,,MLTaskState,,,,,,,,,boolean)

### How can one reproduce the bug?

Attempt to compile the code with current upstream dependencies.

Specifically:
```bash
./gradlew compileTestJava
```
(If it passes, you probably have cached dependencies.)

### What is the expected behavior?

Code compiles.

### What is your host/environment?

Multiple environments failed in https://github.com/opensearch-project/flow-framework/issues/856 but you can probably reproduce it anywhere.

### Do you have any additional context?

The constructor is annotated `@Builder` so we should change that line of code to use a builder (omitting the nulls) to be robust to future changes.

This needs to be fixed promptly and backported to 2.17.

### PR DESCRIPTION
**Pull request by junweid62**
### Description
Ensured compatibility with the new parameter added in [opensearch-project/ml-commons#2825.](https://github.com/opensearch-project/ml-commons/pull/2825)

### Related Issues

Resolves #858

Should fix compile errors causing #856.

### Check List
- [x] New functionality includes testing. (Fixes a test!)
- [x] Commits are signed per the DCO using `--signoff`.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/flow-framework/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/test/java/org/opensearch/flowframework/workflow/DeployModelStepTests.java [hunk 1]
```diff
@@ -215,22 +200,7 @@ public void testDeployModelTaskFailure() throws IOException, InterruptedExceptio
...
-                null,
-                null,
-                null,
-                null,
-                null,
-                "error",
-                null,
-                false
-            );
+            MLTask output = MLTask.builder().taskId(taskId).modelId(modelId).state(MLTaskState.COMPLETED).async(false).build();
```
Comment (dbwiddis) [inline src/test/java/org/opensearch/flowframework/workflow/DeployModelStepTests.java:203]: looks like these are all subtly different parameters so you can't copy paste...

Comment (junweid62) [reply src/test/java/org/opensearch/flowframework/workflow/DeployModelStepTests.java]: changed it

**Review by dbwiddis — APPROVED** [review]
LGTM!  Thanks for the quick fix!

**Review by jackiehanyang — APPROVED** [review]
